server {
    # **************************************************************************** #
    # Define url
    # **************************************************************************** #
    server_name elsr.co.uk www.elsr.co.uk;

    # **************************************************************************** #
    # Serve static content from mounted volume
    # **************************************************************************** #
    root /usr/share/nginx/html/;

    # **************************************************************************** #
    # Connect to Gunicorn container
    # **************************************************************************** #
    location / {
        include /etc/nginx/proxy_params;
        proxy_pass http://elsr:8000;
        proxy_intercept_errors on;

        # Set timeout so we don't just wait for ever if backend is offline
        proxy_connect_timeout 2s;
        proxy_send_timeout 2s;
        proxy_read_timeout 2s;
    }

    # **************************************************************************** #
    # Legacy image path mapping (static → user uploads)
    # **************************************************************************** #
    # Cafe images
    location ^~ /static/img/cafe_photos/ {
        alias /usr/share/nginx/html/user_uploads/cafe_photos/;
        access_log off;
        try_files $uri =404;
    }

    # Classifieds images
    location ^~ /static/img/classifieds_photos/ {
        alias /usr/share/nginx/html/user_uploads/classifieds_photos/;
        access_log off;
        try_files $uri =404;
    }

    # Blog images
    location ^~ /static/img/blog_photos/ {
        alias /usr/share/nginx/html/user_uploads/blog_photos/;
        access_log off;
        try_files $uri =404;
    }

    # **************************************************************************** #
    # Static file behaviour
    # **************************************************************************** #
    # Note fallback to 404 in Flask as Nginx 404 page is crap
    # These are our standard static web page content
    location ~ ^/static/img/ { try_files $uri @fail; }
    location ~ ^/static/css/ { try_files $uri @fail; }
    location ~ ^/static/js/ { try_files $uri @fail; }
    location ~ ^/vendor/ { try_files $uri @fail; }

    # These are the cafe photos which are in the user_uploads mount
    location ~ ^/user_uploads/cafe_photos/ { try_files $uri @fail; }

    # Apple touch icon
    location ~ ^/apple-touch-icon(.*)\.png {
        alias /usr/share/nginx/html/static/img/$1.png;
    }

    # **************************************************************************** #
    # Custom fallback to Flask for nice 404 & logging
    # **************************************************************************** #
    location @fail {
        include /etc/nginx/proxy_params;
        proxy_pass http://elsr:8000;
        proxy_intercept_errors on;
        proxy_connect_timeout 1s;
        proxy_read_timeout 1s;
        proxy_send_timeout 1s;
    }



    # **************************************************************************** #
    # Offline file trigger
    # **************************************************************************** #
    # 502 = Bad Gateway
    # 503 = Service unavailable
    # 504 = Gateway timeout
    error_page 502 503 504 /static/site_offline.html;

    location = /static/site_offline.html {
        internal;
    }


    # **************************************************************************** #
    # Go...
    # **************************************************************************** #
    listen 80;
}
